### PR TITLE
Clarify dd usage

### PR DESCRIPTION
**Pull request by driesvints**
See https://github.com/laravel/octane/issues/131 & https://github.com/laravel/octane/issues/128

### CODE REVIEW

**Comment by barryvdh** [comment]
Or Telescope, the 1st party Laravel tool? :P

**Comment by driesvints** [comment]
@barryvdh added

**Comment by JoshSalway** [comment]
> Or Telescope, the 1st party Laravel tool? :P

@barryvdh What about Laravel Debugbar?

**Comment by barryvdh** [comment]
Hmm I did hear some good things about that as well 🤔

**Review by myckhel — APPROVED** [review]

**Comment by barryvdh** [comment]
Still relevant for dump though.

**Pull request merged**
