### PR TITLE
Fixed Swoole\Http\Response::write(): data to send is empty

### PR DESCRIPTION
**Pull request by lilianjin**

### CODE REVIEW

**Comment by Namoshek** [comment]
How can this even occur with the if above?

**Comment by barryvdh** [comment]
This was fixed with https://github.com/laravel/octane/pull/195 but not yet patched. It occurs when you don't send any response.

**Comment by driesvints** [comment]
Thanks @barryvdh

**Comment by driesvints** [comment]
Patches are on Tuesday

**Pull request closed without merging**
