### PR TITLE
Update swoole's website

### PR DESCRIPTION
**Pull request by sorshion**

### CODE REVIEW

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
That is the wrong swoole. We are using openswoole, not the original.

**Comment by GrahamCampbell** [comment]
https://github.com/openswoole/swoole-src

**Comment by driesvints** [comment]
@GrahamCampbell that's not true. We're offering support for both.

**Comment by nunomaduro** [comment]
I think we should do https://github.com/laravel/octane/pull/441, in favour of this pull request.

**Comment by driesvints** [comment]
@nunomaduro yeah I agree

**Pull request closed without merging**
