### PR TITLE
Add swoole/ide-helper to require-dev

### PR DESCRIPTION
**Pull request by Yurunsoft**
This package contains IDE help files for Swoole. You may use it in your IDE to provide accurate autocompletion.

This package is officially released by Swoole.

### CODE REVIEW

**Comment by crynobone** [comment]
Shouldn't this be as suggested package instead?

**Comment by barryvdh** [comment]
I think it isn't as useful for end-users, but more for developers right? I noticed that PhpStorm didn't understand the Swoole functions, so this could be helpful while developing Octane.

**Comment by Yurunsoft** [comment]
> I think it isn't as useful for end-users, but more for developers right? I noticed that PhpStorm didn't understand the Swoole functions, so this could be helpful while developing Octane.

Yes, you're right

**Comment by themsaid** [comment]
I tried it and it didn't work for me on PHPStorm.

**Comment by Yurunsoft** [comment]
> I tried it and it didn't work for me on PHPStorm.

I use vscode and it works well.

swoole/ide-helper also support phpstorm.

image

**Pull request merged**
