### PR TITLE
Use new static analysis workflow

### PR DESCRIPTION
**Pull request by Jubeki**

### CODE REVIEW

**Comment by driesvints** [comment]
Seems to fail here @Jubeki

**Comment by Jubeki** [comment]
@driesvints I am sorry, no Swoole expert here, maybe somebody with knowledge about Swoole and Octane can take a look and fix it. (Error is unrelated to these changes)

**Comment by driesvints** [comment]
Hi @sy-records. Do you might know why this one occurs?

**Comment by sy-records** [comment]
Missing ext-swoole.

This workflow should allow incoming extensions.

https://github.com/laravel/.github/blob/b28a356e1bd69192b30a23584789274e09d554f2/.github/workflows/static-analysis.yml#L20

**Comment by driesvints** [comment]
@sy-records aaah of course! Thanks a bunch for spotting 👍

**Pull request merged**
