### PR TITLE
[2.x] Add `laravel/prompts`.

### PR DESCRIPTION
**Pull request by xiCO2k**
This PR utilizes the `laravel/prompts` to improve mostly the `$this->choice` and the `$this->confirm` prompts.

Also change the `info`, `warn` and `error` to use the `$this->components` version.

## Before:

https://github.com/laravel/octane/assets/823088/08d739d1-4e35-4e2a-9cea-c99056da018a

## After:

https://github.com/laravel/octane/assets/823088/3a88d9ab-5660-4fae-94ac-4ba504ee490e

Cheers

### CODE REVIEW

**Comment by crynobone** [comment]
@xiCO2k There seem to be a regression based on this PR #918

**Comment by xiCO2k** [comment]
Will take a look on that @crynobone

**Comment by driesvints** [comment]
@xiCO2k did you figure this one out? Otherwise it might be best if we revert for now.

**Comment by xiCO2k** [comment]
Hey @driesvints did not had the time to check it, will try to look during the weekend.

Thanks.

**Comment by xiCO2k** [comment]
@driesvints PR #920 .

**Pull request merged**
